### ISSUE TITLE
MySQL querying UUID

### ISSUE THREAD

**Issue by Schotsl** [denodrivers/mysql#108]
When I query my database to find   a row by it's UUID like this:
```
await this.client.execute(`SELECT uuid, created, updated, title FROM taxonomy WHERE uuid = UNHEX('${uuid}')`);
```

It works just fine! Ofcourse I want to pass the UUID along as a parameter to prevent SQL injection, but when I run the code like this
```
await this.client.execute(`SELECT uuid, created, updated, title FROM \`bot-ross\`.taxonomy WHERE uuid = UNHEX('?')`, [uuid]);
```

It doesn't return a row, while the first snippet does return a row using the same UUID, maybe I misunderstood something but this seems like it should work, right? :(

**Comment by lideming** [comment]
`UNHEX('?')` is wrong, should be `UNHEX(?)`.

**Comment by Schotsl** [comment]
Thank you for your response! When I change `UNHEX('?')` to `HEX(?)` I get this error:

> error: Uncaught (in promise) Error: Unknown column '2467f394f84247368d88a4fa321ae55c' in 'where clause'

This is what the code looks like with the changes

```
await this.client.execute(
   `SELECT HEX(uuid) AS uuid, created, updated, image, firstname, lastname FROM \`bot-ross\`.contact WHERE uuid = UNHEX(?)`,
   [ uuid ]
);
```

But when I run the query in DBeaver it works just fine so it must be an issue with my use of the mysql driver

**Comment by Schotsl** [comment]
I still have this issue, I'd like to know what's wrong with my query if it's not a bug? :(

**Comment by lideming** [comment]
@Schotsl Oops... I thought the problem was solved. Sorry about that.

**Comment by lideming** [comment]
@Schotsl 
I just tried with this code and it worked:
```ts
await client.execute("DROP TABLE IF EXISTS uuids");
await client.execute("CREATE TABLE uuids (uuid BINARY(16) NOT NULL, name VARCHAR(64) NOT NULL)");
await client.execute("INSERT INTO uuids (uuid, name) VALUES (UNHEX(?), ?), (UNHEX(?), ?)", [
    "2467f394f84247368d88a4fa321ae55c", "foo",
    "1234567890abcdef1234567890abcdef", "bar"
]);
console.info(
    await client.query("SELECT HEX(uuid) AS uuid, name FROM uuids WHERE uuid = UNHEX(?);",
        ["2467f394f84247368d88a4fa321ae55c"])
);
```
Output:
```
[ { uuid: "2467F394F84247368D88A4FA321AE55C", name: "foo" } ]
```

**Comment by Schotsl** [comment]
Hmm, that's weird I ran an exact copy of your code (although I did add an primary key since my MySQL server requires it) and it resulted in the same errors:

```
error: Uncaught (in promise) Error: Unknown column '2467f394f84247368d88a4fa321ae55c' in 'field list'
throw new Error(error.message);
```

And this is my modified code:

```
await client.execute("DROP TABLE IF EXISTS uuids");
await client.execute("CREATE TABLE uuids (uuid BINARY(16) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY (uuid))");
await client.execute("INSERT INTO uuids (uuid, name) VALUES (UNHEX(?), ?), (UNHEX(?), ?)", [
    "2467f394f84247368d88a4fa321ae55c", "foo",
    "1234567890abcdef1234567890abcdef", "bar"
]);
console.info(
    await client.query("SELECT HEX(uuid) AS uuid, name FROM uuids WHERE uuid = UNHEX(?);",
        ["2467f394f84247368d88a4fa321ae55c"])
);
```

What version of the `Client` are you using? I'm using this URL https://deno.land/x/mysql/mod.ts

**Comment by lideming** [comment]
@Schotsl I am using the latest version (https://deno.land/x/mysql@v2.9.0/mod.ts).

**Comment by Schotsl** [comment]
Hmm weird, I tried it with the 2.9.0 instead of `x` (although I think they're the same anyway) but I get the same error, I assume this must have too do with a MySQL setting but I don't know what it could be. I'm using a DigitalOcean MySQL instance with no customization..

**Comment by lideming** [comment]
That's really weird... Which SQL statement did the error come from? `INSERT` or `SELECT`?

**Comment by Schotsl** [comment]
p 
,.=-0

**Comment by Schotsl** [comment]
Sorry about the gibberish I posted, must I have accidently hit enter or something. The error is at the `INSERT`, I could pass my database credentials onto you? It's an empty database anyway :)

**Comment by lideming** [comment]
> Sorry about the gibberish I posted, must I have accidently hit enter or something. The error is at the `INSERT`, I could pass my database credentials onto you? It's an empty database anyway :)

Yes, you could send the credential to the email address on my GitHub profile. I will try with it when I have the time today or tomorrow.
Also please tell me the version info about the DB and OS.

**Comment by Schotsl** [comment]
Done!

**Comment by lideming** [comment]
> Done!

I tried with your DB and got the same error. :confused: I will try to address it.

**Comment by lideming** [comment]
So the reason is about `sql_mode` and double-quotes:
https://www.digitalocean.com/community/questions/sql-requests-with-double-quotes-not-working-with-managed-database

With `ANSI_QUOTES` set in `sql_mode`, double-quoted "strings" will be treated as identifiers instead of strings. The driver currently use double-quotes for string values and causes the problem. (The problem is not related to UUID, it happens on all string values.)

There are some solutions:
* (Driver) use single-quotes
* (Driver) automatically detect and remove `ANSI_QUOTES`
* (Workaround) don't set `ANSI_QUOTES` in the DB configuration

**Comment by manyuanrong** [comment]
@lideming Maybe we should replace sql generation with PreparedStatement, so that we can get better query performance in more cases and avoid SQL injection problems

**Comment by lideming** [comment]
> @lideming Maybe we should replace sql generation with PreparedStatement, so that we can get better query performance in more cases and avoid SQL injection problems

@manyuanrong Agreed. That's another protocol to implement.

**Comment by Schotsl** [comment]
Thanks for the help! I'll use the workaround for now and I'll be waiting for the implementation :)
