### ISSUE TITLE
error Deno api connect to mariaDB Database on azure 

### ISSUE THREAD

**Issue by arnobn** [denodrivers/mysql#110]
Im trying to connect with a local deno API on my remote azure database (mariaDB version 10.3) 
but im facing this error : **Currently cannot support auth method mismatch .** 

So after few research on the denodrivers/mysql repository page:  https://github.com/denodrivers/mysql/blob/master/src/connection.ts
<img width="357" alt="error_deno" src="https://user-images.githubusercontent.com/37299156/113878998-64748080-97ba-11eb-93ec-c6dcb49ff272.PNG">

We found out that we are in that case on : 
https://github.com/denodrivers/mysql/blob/e101b49adf5c0a6972acdc4762fe695573fdf7bc/src/packets/parsers/handshake.ts
![image](https://user-images.githubusercontent.com/37299156/113879845-3a6f8e00-97bb-11eb-9ff0-f1d4d14ae178.png)

The denodrivers/mysql repository page said that the error is thrown if  EOF(less than 5.7 or mariadb version is 10.0 or 10.1)
![image](https://user-images.githubusercontent.com/37299156/113880514-da2d1c00-97bb-11eb-97b1-6be651c15785.png)
 
but as i said at the beginning we are on 10.3 for mariaDB so im a bit lost of how am i suppose to connect to our db.

 Here the code without password and hostname : 
![image](https://user-images.githubusercontent.com/37299156/113882318-7b68a200-97bd-11eb-9de6-fc95535b249a.png)

**Comment by lideming** [comment]
The driver currently doesn't support [Authentication Method Mismatch](https://dev.mysql.com/doc/dev/mysql-server/8.0.12/page_protocol_connection_phase.html#sect_protocol_connection_phase_auth_method_mismatch). We need to implement it to fix the problem.

**Comment by boonook** [comment]
Hello, may I ask if the problem has been solved?

**Comment by lideming** [comment]
Should be fixed by #137. Please reopen this issue if the problem still occurs.
