### ISSUE TITLE
Changes to support big data actions

### ISSUE THREAD

**Issue by hktr92** [denodrivers/mysql#111]
Hello.

I've ported a low-level task from PHP to Deno. Using this lib, I managed successfully performing all that it needs to be done in the business logic side.

I've encountered an issue on our production machine caused by an out of memory kill. We're trying to swift through a ton of data.

After a quick debug, I've noticed that the `connection.execute()` collects the result in an array. For dealing with such volume of data, having a generator helps a lot.

I've forked the lib here: https://github.com/hktr92/mysql and started to work on a solution. For now, I only added an extra method that does the same thing as `execute` but it `yield`s the parsed row.

This operation can be performed **only** by `SELECT`s, e.g.:
```js
const sql = "SELECT * FROM foo"

const generator = await client.execute_generator(sql)
for await (const row of generator) { 
    // handle row.value here
}
```

I'm thinking that this method would yield only the actual row from database instead of `{ row, fields }`, as it doesn't make any sense to return such information from AsyncIterator.

Once it's stable enough, I'll make a PR and apply additional changes to the code in order to be ready to merge and switch in various implementations without any fuss. I don't really have an ETA on when I'm finishing this, though.

My POV is that it ain't that much code to be changed. After I'm implementing the async generator, to prevent duplicate code, the `execute` method could collect the `execute_generator` values and return the array.

I'm open to discussions about my proposed changes.

**Comment by lideming** [comment]
I think these changes are great! PRs are welcomed.

I am thinking that the method could return `{ iterator, fields }` if there is a query, otherwise `{ lastInsertId, affectedRows }` .
