### ISSUE TITLE
error: TS2416 [ERROR]: Property 'name' in type 'PartialReadError' in DENO v1.13.0

### ISSUE THREAD

**Issue by koanzen** [denodrivers/mysql#117]
Getting Error to new version of Deno 1.13.0, By Just Connecting to MySQL Database

error: TS2416 [ERROR]: Property 'name' in type 'PartialReadError' is not assignable to the same property in base type 'UnexpectedEof'.
  Type 'string' is not assignable to type '"UnexpectedEof"'.
  name = "PartialReadError";
  ~~~~
 at https://deno.land/std@0.74.0/io/bufio.ts:27:3

**Comment by lideming** [comment]
Fixed in v2.10.0, thanks!

**Comment by chovy** [comment]
how do i upgrade?
