### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by Schotsl** [denodrivers/mysql#122]
I've tested the latest version of this package by importing in using the GitHub URL in Deno, and https://github.com/denodrivers/mysql/issues/115 has been fixed by https://github.com/denodrivers/mysql/pull/121.

Can a hotfix version be released for deno.land? :)

**Comment by lideming** [comment]
[v2.10.1](https://github.com/denodrivers/mysql/releases/tag/v2.10.1) have been released.
