### ISSUE TITLE
Can not import Module

### ISSUE THREAD

**Issue by DVDope** [denodrivers/mysql#126]
When trying to import the module like 
```
import { Client } from "https://deno.land/x/mysql@v2.10.2/mod.ts";
```
I get an error my browser and no content gets displayed. 
```
wasm.js:214 Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
    at wasm.js:214:20
```

I tried with 
* Google Chrome
* Microsoft Edge

Any ideas on how to fix this issue?

**Comment by lideming** [comment]
Are you trying to use the module in browsers? This module is for the Deno runtime, not for browsers.

**Comment by DVDope** [comment]
Yes thank you! I didn't realize this at first
