### ISSUE TITLE
Unknown column error

### ISSUE THREAD

**Issue by Schotsl** [denodrivers/mysql#127]
I've created a database using this statement:

```
CREATE TABLE location (
	uuid BINARY(16) NOT NULL,
	image BINARY(16),
	
	title VARCHAR(255) NOT NULL,

	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY (uuid)
);
```

Then I connect to the database using the example from the README.md:

```
import { Client } from "https://deno.land/x/mysql@v2.10.2/mod.ts";

const client = await new Client().connect({
  ...
});
```

Now when I try to insert using this query:

```
client.execute(
  "INSERT INTO location (`uuid`, `title`) VALUES (UNHEX(REPLACE(?, '-', '')), ?)",
  ["c0b9811e-c680-45ef-a305-e0c1475ff7c4", "Lucas Bolsstraat 24/7"],
);
```

I get this error:

> error: Uncaught (in promise) Error: Unknown column 'c0b9811e-c680-45ef-a305-e0c1475ff7c4' in 'field list'

I did some research and it appears this happens most often when quotation marks are missing. Which is weird since this query used to work and I assumed mysql added the quotation marks. Anyhow I tried to fix the query:

```
client.execute(
  "INSERT INTO location (`uuid`, `title`) VALUES (UNHEX(REPLACE('?', '-', '')), '?')",
  ["c0b9811e-c680-45ef-a305-e0c1475ff7c4", "Lucas Bolsstraat 24/7"],
);
```

Although this throws a new error:

> error: Uncaught (in promise) Error: Incorrect string value: 'replace('?','-','')' for function unhex

Is there a way to fix this issue, the query works fine when running it from dbeaver. So I'm fairly sure that it's an issue with the mysql package? I'm running Deno 1.19.0

**Comment by lideming** [comment]
I guess it's the same problem as https://github.com/denodrivers/mysql/issues/108 ?

**Comment by Schotsl** [comment]
My bad! I completely forgot I changed the database rules on my old database as a work around, sorry for bothering with the same issue!
