### ISSUE TITLE
Dose not work with MySQL-compitable Database

### ISSUE THREAD

**Issue by shiyuhang0** [denodrivers/mysql#136]
I use deno driver to connect to TiDB, a MySQL-compatible Database. But find the result is empty.

TiDB works with most of the MySQL drivers including https://github.com/sail-sail/mysql2.

I think there may some thing different with https://github.com/sail-sail/mysql2.

Reproduce:
1. Build a TiDB with the following command
```
curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
```
```
source ${your_shell_profile}
```
```
tiup playground v6.1.0
```
2. Connect to TiDB with the driver
```
import { Client } from "https://deno.land/x/mysql/mod.ts";

const client = await new Client().connect({
  hostname: "127.0.0.1",
  username: "root",
  db: "test",
  password: "",
  port: 4000
});

const result = await client.query('show databases');
console.log(result);
```

**Comment by shiyuhang0** [comment]
I have found the answer. TiDB still return the EOF package before v6.3.0, cause

**Comment by shiyuhang0** [comment]
Maybe we can refer other drivers who can support both case (EOF and deprecated EOF ), the original logic may miss some thing like TiDB.

**Comment by lideming** [comment]
Could you confirm whether #139 fixed this?

**Comment by shiyuhang0** [comment]
Yes, I have prepared a pr for this too. It is similar as https://github.com/denodrivers/mysql/pull/139.
