### ISSUE TITLE
Error: ProtocolError on MariaDB 10.10.3

### ISSUE THREAD

**Issue by Merulast** [denodrivers/mysql#153]
Hi, I use arch linux and had monday an update up to `mariadb  Ver 15.1 Distrib 10.10.3-MariaDB, for Linux (x86_64) using readline 5.1`. 

Since then its impossible to do anything on the db. I could connect, but as soon as something get executed I hit 
```
Error
    at PoolConnection.execute (https://deno.land/x/mysql@v2.10.3/src/connection.ts:293:17)
    at async PoolConnection.query (https://deno.land/x/mysql@v2.10.3/src/connection.ts:239:20)
    at async https://deno.land/x/mysql@v2.10.3/src/client.ts:86:14
    at async Client.useConnection (https://deno.land/x/mysql@v2.10.3/src/client.ts:107:14)
    at async Client.query (https://deno.land/x/mysql@v2.10.3/src/client.ts:85:12)
    at async file:///home/tharo/dev/pudding-backend/test.ts:10:1
```  

According to the source-code it looks like an issue by design. But my understanding of mariadb interna is not enought to understand why this if clause is there. The java drivers (used in DBeaver) and the php ones (`PHP 8.2.2 (cli) (built: Feb  1 2023 08:33:04) (NTS)`) had no issue with the new mariadb version. 
Anyway. I think that soon many people might run into this issue. So I hope it get fixed soon. 

Thanks for your great work.

**Comment by lideming** [comment]
Hi, did you try the latest version ([v2.11.0](https://github.com/denodrivers/mysql/releases/tag/v2.11.0))? We have fixed the handling of `EOF_Packet`.

**Comment by Merulast** [comment]
Thats true. Thank you.
