### ISSUE TITLE
Use node mysql or deno mysql?

### ISSUE THREAD

**Issue by shiyuhang0** [denodrivers/mysql#161]
Hi, Deno supports using the npm package since 1.28. which means node mysql2 is available in deno runtime.

So， how will the deno driver develop？ Does it mean the deno drivers such as MySQL driver is no longer needed above deno 1.28？

**Comment by DMeechan** [comment]
@shiyuhang0 I'm not sure how well mysql2 currently runs on Deno. Right now mysql2 on Deno 1.36.1 throws an error when using TLS (https://github.com/denoland/deno/issues/20293)

**Comment by shiyuhang0** [comment]
It looks like Deno still has a long way to go to the node compatibility. Deno driver may still be necessary. Thanks for your reply!
