### ISSUE TITLE
[SUGGESTION] Add topics

### ISSUE THREAD

**Issue by Julien-Broyard** [denodrivers/mysql#44]
Hey, I was thinking to add topics in order to make this repository more visible. 
Is this something you would want ?

**Comment by manyuanrong** [comment]
Yes, please

**Comment by Julien-Broyard** [comment]
![image](https://user-images.githubusercontent.com/35043096/82115589-008d3780-9764-11ea-8a2f-f3a8b1e4a87f.png)

However I can't do it on a pull request so you're the only able to dit. You need to click on manage topics

**Comment by manyuanrong** [comment]
Sorry, I don’t seem to understand what you mean. Is this a feature of Github?

**Comment by Julien-Broyard** [comment]
Yes it is
