### ISSUE TITLE
Connection failure does not throw error

### ISSUE THREAD

**Issue by jerrythomas** [denodrivers/mysql#45]
The following code snippet does not raise any error when the MySQL server is not running or if it refuses the connection.

```ts
      try {
        const db = await new Client().connect({username: "root"});
      } catch (err) {
        console.error(err);
      }
```

The error is raised only when a query is fired. 
```ts
      try {
        const db = await new Client().connect({username: "root"});
        const result = await db.query("show variables like 'version';")
      } catch (err) {
        console.error(err);
      }
```

Is this intended behaviour? If yes why does creating the connection not throw an error? It also does not show the error that it is accessing the localhost URL when running without any permissions.

**Comment by sarthaksavvy** [comment]
I am also getting Same error 

`
error: Uncaught Error: Not supported
      throw new Error("Not supported");
`

mysql --version
mysql  Ver 8.0.19 for osx10.15 on x86_64

**Comment by manyuanrong** [comment]
@sarthaksavvy Currently does not support the default authentication plugin for mysql 8.0 #37

**Comment by sarthaksavvy** [comment]
@manyuanrong thanks man, waiting for mysql 8 support, please do it fast

**Comment by lideming** [comment]
It is intended. `new Client().connect()` does not create the connection but the connection pool.
