### ISSUE TITLE
Abstract nextPacket from Connection

### ISSUE THREAD

**Issue by invisal** [denodrivers/mysql#52]
I was trying to implement `cache_sha2_password`. Since `cache_sha2_password` need several communication back and fore, it is not possible to do it with current `buildAuth`.

I think it is better for us to have ability to pass connection and use `nextPacket`. But since `nextPacket` is private, it is not possible to use it inside the `handleHandshake`.

```javascript
export class Connection {
  //...
  private async _connect() {
      // ....
      await handleHandshake(this, this.client.config);
      // ....
  }
}
```

Another way we wrap the raw connection with another helper class. Then we just pass helper class to other function.

```javascript
class ConnectionHelper {
   next(): Promise<RecievePacket>
   send(data, sequence?: number): Promise<void>
   startTls() // for future SSL support implementation
}
```
Then in the `Connection` class

```javascript
class Connection {
    private raw: Deno.Conn;
    private conn: ConnectionHelper;

    private async _connect() {
       // ....
      this.conn = new ConnectionHelper(raw);
      await handleHandshake(this.conn, this.client.config);
      // ....
    }
}
```

**Comment by manyuanrong** [comment]
I think it is ok

**Comment by wenjoy** [comment]
@invisal What's the progress on it? Have u r alreday working on a branch? I also would like to give a hand.
