### ISSUE TITLE
InvalidData: data did not match any variant of untagged enum ArgsEnum

### ISSUE THREAD

**Issue by danbulant** [denodrivers/mysql#59]
Hello there

I was using this module before on linux on Deno 1.1.0 with no problems, but when I switched to windows (with different deno code), I started getting this error:

```
INFO connecting api.iceproductions.dev:3306
Error loading table data: InvalidData: data did not match any variant of untagged enum ArgsEnum
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.connect ($deno$/net.ts:182:11)
    at async Connection._connect (https://deno.land/x/mysql/src/connection.ts:45:17)
    at async Connection.connect (https://deno.land/x/mysql/src/connection.ts:82:5)
    at async Client.createConnection (https://deno.land/x/mysql/src/client.ts:45:5)
    at async DeferredStack.pop (https://deno.land/x/mysql/src/deferred.ts:33:20)
    at async Client.useConnection (https://deno.land/x/mysql/src/client.ts:109:24)
    at async Client.query (https://deno.land/x/mysql/src/client.ts:89:12)
```

I have no idea why, and the only thing I found was on SO telling me to never use master branch, rather use release with version support, however using latest release (2.2.0) didn't change anything. Any ideas if I'm doing something wrong?

My code is (when simplified)
```
const pool = await new Client().connect({
    hostname: config.mysql.host,
    username: config.mysql.username,
    db: config.mysql.database,
    password: config.mysql.password,
    port: config.mysql.port
});


var resp = await pool.query("SHOW tables"); // <-- fails here
```

All of config is from user input, everything except port is of type string.

Versions: 
```
   12GB RAM (11.9GB usable),
    Intel i5
    Win 10 (v2004, build 19041.239)
    deno 1.1.0
    v8 8.4.300
    typescript 3.9.2
    10.4.12-MariaDB-1:10.4.12+maria~bionic-log
```
Note that the same server (MariaDB) worked just fine when connecting from linux (and in fact, I'm connected to it right now from local adminer so connection itself should work too).

**Comment by danbulant** [comment]
Update: turns out this happens on linux (tested via glitch) too. I have no idea why.

**Comment by danbulant** [comment]
Update: I updated to deno 1.1.1, issue still persists

**Comment by manyuanrong** [comment]
At present, I am not sure from the error message whether it is caused by the new changes of Deno. Is it normal in the previous Deno version?

**Comment by danbulant** [comment]
I haven't seen this error before, and from searching the only reason I found is that the library used (in the case I found, postgres) wasn't compatible with that deno version (which doesn't help at all when trying to fix it).

This looks like it happens on Deno 1.1+ on both windows and linux (even on fresh installs), so it really looks like some compatibility thing. What's weird is that I couldn't find any enum on the line mentioned - it has `Deno.connect` call with hostname, port and `transport = 'tcp'` (which is the only possible value as of now). You can view source [here](https://github.com/manyuanrong/deno_mysql/blob/master/src/connection.ts#L45-L49).

**Comment by danbulant** [comment]
Update: I maybe found a thing - it may be relevant to denoland/deno#5700, as we both use `--unstable` flag. It looks like TCP connections (both `connect` and `listen`) have this bug when using `--unstable` flag. I'll close this issue since it's issue on deno's (and my) side.

**Comment by danbulant** [comment]
Still happens even without --unstable.... I have no idea why. Does anyone have same problem as me (with using this module in deno 1.1.1)?

**Comment by jpeterse** [comment]
I ran into this issue today, using Deno 1.2.0 and mySQL 2.3.0.

It happens when port number is provided as a string. Specifying the port number as a number, solves the issue.

**Comment by danbulant** [comment]
to help the maintainers, I'll close the issue (I'm no longer using mysql and this issue was stale for while).
