### ISSUE TITLE
Replace checksum and sha256 with std/hash

### ISSUE THREAD

**Issue by invisal** [denodrivers/mysql#69]
Should we replace

```
export { Hash } from "https://deno.land/x/checksum@1.4.0/mod.ts";
export { sha256 } from "https://deno.land/x/sha256@v1.0.2/mod.ts";
```

with https://deno.land/std@0.63.0/hash as it is official hash and it supports both Hash and sha256.

**Comment by lideming** [comment]
They are replaced in commit https://github.com/denodrivers/mysql/commit/613a4317724a672bf7c4538159c66654088d8d4b .
