### ISSUE TITLE
Moving: Under an Org

### ISSUE THREAD

**Issue by ebebbington** [denodrivers/mysql#88]
Hey! :)  I've been speaking about deno drivers in the deno discord, and thought it might be a good idea to have a single org to hold all drivers (sql, mongo, redis etc), eg `denodrivers/postgres`, `.../mongo`, `.../sql`, `../sqlite`. I was curious on how you felt about moving your sqlite repo? The idea came about as the mongo driver for deno is unmaintained now (and a deno plugin so very unstable), and there's a few people saying 'oh i can't do it, it's too much work', so myself and @qu4k have put together an org and discord. Then it'd be amazing if all drivers were under a single roof.

Of course i wouldn't be the leader for the repo, we have teams within the org and channels within the discord to keep the division (so i have no role in redis which i should have really)

The end result is the deno community can develop stable drivers, and them being all under one roof

Let me know what you think :)

- [x] mongod
- [x] sqlite
- [x] postgres
- [ ] pgc4d (possibility)
- [ ] redis (asked, no response yet)

Links:
Org: https://github.com/denodrivers
Discord: https://discord.gg/FHtas8

Thanks, Edward

**Comment by manyuanrong** [comment]
Yes, I am willing to do so. but Discord invitation link seems to be invalid.

**Comment by ebebbington** [comment]
My bad! https://discord.gg/r5WZ485

Obviously take your time and do everything when you’re ready :) Just mention you’re the author of sql in the discord and well give (and anyone else who is a maintainer too) the MySQL role
